Repository ucsb-cs156-w24/proj-happy-cows-w24-4pm-1, pull requests merged in 2024-03, with the labels that each got.

#1 AJ -- fix typo in gamePlay.md
  docs/gamePlay.md
Labels: 5

#20 Added whitespace
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
Labels: 5

#19 added pagination to OurTable - LG
  frontend/src/main/components/OurTable.js
  frontend/src/tests/components/OurTable.test.js
Labels: 10

#21 fix bug negative cows sold
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: bug, 10

#22 Lg buycow
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: bug, 10

#30 B1: Backend Entity/Repo Epic: Add Announcements
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcements.java
  src/test/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementsRepository.java
Labels: 5

#31 F1: Table and form, Epic: Add Announcements
  frontend/src/fixtures/announcementsFixtures.js
  frontend/src/main/components/Announcements/AnnouncementsForm.js
  frontend/src/main/components/Announcements/AnnouncementsTable.js
  frontend/src/main/utils/announcementsUtils.js
  frontend/src/stories/components/Announcements/AnnouncementsForm.stories.js
  frontend/src/stories/components/Announcements/AnnouncementsTable.stories.js
  frontend/src/tests/components/Announcements/AnnouncementsForm.test.js
  frontend/src/tests/components/Announcements/AnnouncementsTable.test.js
  frontend/src/tests/utils/announcementsUtils.test.js
Labels: 10

#36 B2: Swagger Endpoints (Post, Get, Put, Delete), Epic: Add Announcements
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 20
